[nitpick]
minimum_version = "0.22.0"

[nitpick.styles]
include = [
  "file-structure.toml",
  "flake8.toml",
  "isort.toml",
  "darglint.toml",
  "mypy.toml",
  "poetry.toml",
  "styleguide.toml",
  "coverage.toml"
]